### ISSUE TITLE
Infusion does not account for amount of max HP received per stack

### ISSUE THREAD

**Issue by roncli** [stefanuros/ror2-item-cheat-sheet#12]
Infusion was buffed a few patches ago to allow you to accumulate max HP faster the more stacks you have.

Currently: "Killing an enemy increases your health permanently by 1, up to a maximum of 100 (+100 per stack) health."

What happens in game: "Killing an enemy increases your health permanently by 1 (+1 per stack), up to a maximum of 100 (+100 per stack) health."

Stacking is linear... ie: 7 stacks will increase your max HP by 7 per kill.

**Comment by stefanuros** [comment]
Very interesting, I was not aware. I'll be sure to update it, and double-check others I may have missed. Thanks for letting me know!
